### ISSUE TITLE
Exception when using `Registry Explorer` toolbar in PyCharm 

### ISSUE THREAD

**Issue by CoonCat21** [ExidCuter/docker-registry-explorer-plugin#3]
# Assertion fails when attempting to use the _Registry Explorer_ toolbar in PyCharm 

Registry Explorer fails to load a registry and the IDE reports an empty error baloon along with a built-in balloon indicating an error occurred.

## Details
When loading a docker registry, an empty Balloon error message is displayed and PyCharm reports an _IDE error occurred_, in a separate Balloon.

![image](https://user-images.githubusercontent.com/69431253/117838491-62359400-b248-11eb-84b4-bc93d884557b.png)

Clicking on the IDE Error balloon's _See details and submit report_ link, I'm presented with PyCharm's IDE Fatal Errors dialog which lets me know that error reporting is not implemented for DockerRegistry.

![image](https://user-images.githubusercontent.com/69431253/117839951-b2612600-b249-11eb-9819-18e107001565.png)

## Occurrences

This occurs under all of the following circumstances:
1. Immediately after adding a registry by clicking _+_ in the _Registry Explorer_ toolbar and entering `username`, `password`, and `registry URL` into the dialog and clicking `OK`
![image](https://user-images.githubusercontent.com/69431253/117841537-25b76780-b24b-11eb-8812-46e2361de15a.png)
2. After clicking the _Refresh Registry Listing_ button
 on the _Registry Explorer_ toolbar with a registry already configured.
![image](https://user-images.githubusercontent.com/69431253/117842114-a0808280-b24b-11eb-9ba5-ad12e4f3f235.png)
3. When loading a project after already having a registry configured.

## Expectations

1. Entering or loading a previously entered Registry results in no error message and a listing of registry artifacts.
2. If an error does occur the ability to submit an error report from the IDE would be nice. I know this should be a separate issue and will gladly create a new one, if you prefer.

## IDE and Stack Trace

PyCharm 2021.1.1 (Professional Edition)
Build #PY-211.7142.13, built on April 21, 2021
Runtime version: 11.0.10+9-b1341.41 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Non-Bundled Plugins: com.github.exidcuter.dockerregistryexplorer (1.0.3-stable)

[Stack Trace ](https://github.com/ExidCuter/docker-registry-explorer-plugin/files/6460229/202105111056-DockerRegistry.PyCharm.stacktrace.txt)

**Comment by CoonCat21** [comment]
It turns out the actual error is that a trailing forward-slash on the URL seems to break the pluging.

`https://registry.local/` breaks, while `https://registry.local` works without issue, however.

**Comment by silicispongia** [comment]
Same error in Idea ultimate 2021.1.2

Registry url is http and has a port. Like so:
http://registry.foo.bar:5000

```
java.lang.Throwable: Assertion failed: Notification should have title and/or content; groupId: DockerRegistry Notifications
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:197)
	at com.intellij.notification.Notification.assertHasTitleOrContent(Notification.java:421)
	at com.intellij.notification.Notifications$Bus.notify(Notifications.java:73)
	at com.intellij.notification.Notification.notify(Notification.java:399)
	at com.github.exidcuter.dockerregistryexplorer.ui.RegistryErrorNotifier.notifyError(RegistryErrorNotifier.java:13)
	at com.github.exidcuter.dockerregistryexplorer.ui.ExplorerToolWindowFactory.lambda$fetchData$2(ExplorerToolWindowFactory.java:109)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.github.exidcuter.dockerregistryexplorer.ui.ExplorerToolWindowFactory.fetchData(ExplorerToolWindowFactory.java:92)
	at com.github.exidcuter.dockerregistryexplorer.ui.ExplorerToolWindowFactory.refreshTree(ExplorerToolWindowFactory.java:82)
	at com.github.exidcuter.dockerregistryexplorer.ui.ExplorerToolWindowFactory.editButtonPressed(ExplorerToolWindowFactory.java:141)
	at com.intellij.ui.ToolbarDecorator$3.doEdit(ToolbarDecorator.java:535)
	at com.intellij.ui.CommonActionsPanel$EditButton.actionPerformed(CommonActionsPanel.java:366)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAware$5(ActionUtil.java:273)
	at com.intellij.util.SlowOperations.lambda$allowSlowOperations$0(SlowOperations.java:77)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:64)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:76)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:273)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:201)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:174)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:157)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:469)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:836)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by ExidCuter** [comment]
Hi, new build with fixes was submitted to the JetBrains store. It normally takes 1-2 days to accept it.
